@import hexlet.code.dto.UrlsPage
@import hexlet.code.util.NamedRoutes

@param UrlsPage page

@template.layout.page(
    page = page,
    content = @`
    <h1>Сайты</h1>
    <table class="table table-bordered" data-test="urls">
      <thead>
        <tr>
          <th>ID</th>
          <th>Имя</th>
          <th>Дата создания</th>
          <th>Код ответа</th>
        </tr>
      </thead>
      <tbody>
        @for(var url : page.getUrls())
        <tr>
          <td>${url.getId()}</td>
          <td><a href="${NamedRoutes.urlPath(url.getId())}">${url.getName()}</a></td>
          <td>${url.getFormattedCreatedAt()}</td>
          <td></td>
        </tr>
        @endfor
      </tbody>
    </table>
    `
)
